<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'qr_code' => 'PRD001',
                'name' => 'Bàn phím Logitech K120',
                'sku' => 'KB-LOGI-K120',
                'price' => 180000,
                'stock' => 35,
                'type' => 1,
                'location' => 'Kho A - Kệ 01',
                'description' => 'Bàn phím USB dùng cho văn phòng',
            ],
            [
                'qr_code' => 'PRD002',
                'name' => 'Chuột Logitech M90',
                'sku' => 'MS-LOGI-M90',
                'price' => 120000,
                'stock' => 50,
                'type' => 1,
                'location' => 'Kho A - Kệ 01',
                'description' => 'Chuột quang USB',
            ],
            [
                'qr_code' => 'PRD003',
                'name' => 'Màn hình Dell 24 inch',
                'sku' => 'MN-DELL-24',
                'price' => 2800000,
                'stock' => 12,
                'type' => 2,
                'location' => 'Kho A - Kệ 02',
                'description' => 'Màn hình văn phòng 24 inch',
            ],
            [
                'qr_code' => 'PRD004',
                'name' => 'Laptop Dell Latitude 5420',
                'sku' => 'LT-DELL-5420',
                'price' => 12500000,
                'type' => 3,
                'stock' => 8,
                'location' => 'Kho B - Kệ 01',
                'description' => 'Laptop Dell dùng cho nhân viên',
            ],
            [
                'qr_code' => 'PRD005',
                'name' => 'Adapter Dell 65W',
                'sku' => 'AD-DELL-65W',
                'price' => 450000,
                'type' => 1,
                'stock' => 20,
                'location' => 'Kho B - Kệ 02',
                'description' => 'Sạc laptop Dell 65W',
            ],
            [
                'qr_code' => 'PRD006',
                'name' => 'Cáp HDMI 1.5m',
                'sku' => 'CB-HDMI-15',
                'price' => 80000,
                'stock' => 60,
                'type' => 2,
                'location' => 'Kho C - Kệ 01',
                'description' => 'Cáp HDMI dài 1.5 mét',
            ],
            [
                'qr_code' => 'PRD007',
                'name' => 'Cáp mạng LAN Cat6 3m',
                'sku' => 'CB-LAN-CAT6-3M',
                'price' => 60000,
                'stock' => 100,
                'type' => 3,
                'location' => 'Kho C - Kệ 01',
                'description' => 'Cáp mạng Cat6 dài 3 mét',
            ],
            [
                'qr_code' => 'PRD008',
                'name' => 'USB Kingston 32GB',
                'sku' => 'USB-KING-32',
                'price' => 130000,
                'stock' => 45,
                'type' => 1,
                'location' => 'Kho C - Kệ 02',
                'description' => 'USB lưu trữ dung lượng 32GB',
            ],
            [
                'qr_code' => 'PRD009',
                'name' => 'Ổ cứng SSD Kingston 240GB',
                'sku' => 'SSD-KING-240',
                'price' => 550000,
                'stock' => 18,
                'type' => 1,
                'location' => 'Kho C - Kệ 03',
                'description' => 'SSD SATA 240GB',
            ],
            [
                'qr_code' => 'PRD010',
                'name' => 'RAM DDR4 8GB',
                'sku' => 'RAM-DDR4-8G',
                'price' => 480000,
                'stock' => 22,
                'type' => 4,
                'location' => 'Kho C - Kệ 03',
                'description' => 'RAM DDR4 8GB cho máy tính',
            ],
            [
                'qr_code' => 'PRD011',
                'name' => 'Máy in Canon LBP 2900',
                'sku' => 'PR-CANON-2900',
                'price' => 3200000,
                'stock' => 5,
                'type' => 2,
                'location' => 'Kho D - Kệ 01',
                'description' => 'Máy in laser trắng đen',
            ],
            [
                'qr_code' => 'PRD012',
                'name' => 'Mực in Canon 303',
                'sku' => 'INK-CANON-303',
                'price' => 350000,
                'stock' => 30,
                'type' => 2,
                'location' => 'Kho D - Kệ 02',
                'description' => 'Hộp mực cho máy in Canon 2900',
            ],
            [
                'qr_code' => 'PRD013',
                'name' => 'Giấy in A4 Double A',
                'sku' => 'PAPER-A4-DA',
                'price' => 85000,
                'stock' => 120,
                'type' => 1,
                'location' => 'Kho D - Kệ 03',
                'description' => 'Giấy in A4 định lượng 70gsm',
            ],
            [
                'qr_code' => 'PRD014',
                'name' => 'Bút bi Thiên Long xanh',
                'sku' => 'PEN-TL-BLUE',
                'price' => 5000,
                'stock' => 300,
                'type' => 3,
                'location' => 'Kho E - Kệ 01',
                'description' => 'Bút bi màu xanh',
            ],
            [
                'qr_code' => 'PRD015',
                'name' => 'Sổ tay A5',
                'sku' => 'NOTE-A5',
                'price' => 25000,
                'stock' => 80,
                'type' => 3,
                'location' => 'Kho E - Kệ 02',
                'description' => 'Sổ tay văn phòng khổ A5',
            ],
            [
                'qr_code' => 'PRD016',
                'name' => 'Băng dính trong',
                'sku' => 'TAPE-CLEAR',
                'price' => 12000,
                'stock' => 90,
                'type' => 1,
                'location' => 'Kho E - Kệ 03',
                'description' => 'Băng dính trong dùng đóng gói',
            ],
            [
                'qr_code' => 'PRD017',
                'name' => 'Ổ cắm điện 5 cổng',
                'sku' => 'POWER-5PORT',
                'price' => 150000,
                'stock' => 25,
                'type' => 1,
                'location' => 'Kho F - Kệ 01',
                'description' => 'Ổ cắm kéo dài 5 cổng',
            ],
            [
                'qr_code' => 'PRD018',
                'name' => 'Pin AA Panasonic',
                'sku' => 'BAT-AA-PANA',
                'price' => 20000,
                'stock' => 150,
                'type' => 1,
                'location' => 'Kho F - Kệ 02',
                'description' => 'Pin AA dùng cho thiết bị văn phòng',
            ],
            [
                'qr_code' => 'PRD019',
                'name' => 'Tai nghe Logitech H111',
                'sku' => 'HP-LOGI-H111',
                'price' => 220000,
                'stock' => 16,
                'type' => 1,
                'location' => 'Kho B - Kệ 03',
                'description' => 'Tai nghe có micro dùng họp online',
            ],
            [
                'qr_code' => 'PRD020',
                'name' => 'Webcam Logitech C270',
                'sku' => 'WC-LOGI-C270',
                'price' => 650000,
                'stock' => 10,
                'type' => 1,
                'location' => 'Kho B - Kệ 03',
                'description' => 'Webcam HD dùng họp trực tuyến',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['qr_code' => $product['qr_code']],
                $product
            );
        }
    }
}
