<?php

namespace Database\Seeders;

use App\Models\CaseFile;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $case1 = CaseFile::where('case_code', 'HS0001')->first();
        $case2 = CaseFile::where('case_code', 'HS0002')->first();
        $case3 = CaseFile::where('case_code', 'HS0003')->first();

        $products = [
            [
                'case_file_id' => optional($case1)->id,
                'qr_code' => 'HS0001-VC001',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Dao kim loại thu tại hiện trường',
                'sku' => 'VC-A-001',
                'location' => 'Tủ vật chứng A - Ngăn 01',
                'description' => 'Dao kim loại dài khoảng 20cm, đã niêm phong.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case1)->id,
                'qr_code' => 'HS0001-VC002',
                'type' => Product::TYPE_DOCUMENT,
                'name' => 'Biên bản ghi nhận hiện trường',
                'sku' => 'VC-A-002',
                'location' => 'Tủ hồ sơ A - Ngăn 02',
                'description' => 'Biên bản giấy thu giữ tại hiện trường.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case1)->id,
                'qr_code' => 'HS0001-VC003',
                'type' => Product::TYPE_IMAGE,
                'name' => 'Ảnh chụp dấu vết hiện trường',
                'sku' => 'VC-A-003',
                'location' => 'Ổ lưu trữ số 01',
                'description' => 'Bộ ảnh chụp hiện trường được sao lưu.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case1)->id,
                'qr_code' => 'HS0001-VC004',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Mảnh vải màu đen',
                'sku' => 'VC-A-004',
                'location' => 'Tủ vật chứng A - Ngăn 03',
                'description' => 'Mảnh vải nhỏ thu tại khu vực cửa ra vào.',
                'storage_status' => Product::STORAGE_STATUS_ASSESSMENT,
                'stock' => 0,
            ],
            [
                'case_file_id' => optional($case1)->id,
                'qr_code' => 'HS0001-VC005',
                'type' => Product::TYPE_DIGITAL,
                'name' => 'USB màu trắng',
                'sku' => 'VC-A-005',
                'location' => 'Tủ điện tử E - Ngăn 01',
                'description' => 'USB dung lượng 32GB, đã niêm phong.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],

            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC001',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Túi nylon chứa mẫu bột',
                'sku' => 'VC-B-001',
                'location' => 'Tủ định kho - Ngăn 01',
                'description' => 'Túi nylon trong suốt chứa mẫu bột, đã niêm phong.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC002',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Hộp carton nhỏ',
                'sku' => 'VC-B-002',
                'location' => 'Kho vật chứng B - Kệ 01',
                'description' => 'Hộp carton thu tại kho hàng.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC003',
                'type' => Product::TYPE_DOCUMENT,
                'name' => 'Phiếu xuất kho bản giấy',
                'sku' => 'VC-B-003',
                'location' => 'Tủ hồ sơ B - Ngăn 04',
                'description' => 'Phiếu xuất kho liên quan đến vụ việc.',
                'storage_status' => Product::STORAGE_STATUS_RETURNED,
                'stock' => 0,
            ],
            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC004',
                'type' => Product::TYPE_DIGITAL,
                'name' => 'Ổ cứng di động',
                'sku' => 'VC-B-004',
                'location' => 'Tủ điện tử E - Ngăn 02',
                'description' => 'Ổ cứng di động màu đen.',
                'storage_status' => Product::STORAGE_STATUS_ASSESSMENT,
                'stock' => 0,
            ],
            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC005',
                'type' => Product::TYPE_IMAGE,
                'name' => 'Ảnh camera kho hàng',
                'sku' => 'VC-B-005',
                'location' => 'Ổ lưu trữ số 02',
                'description' => 'Ảnh trích xuất từ camera kho hàng.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC006',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Tem niêm phong bị rách',
                'sku' => 'VC-B-006',
                'location' => 'Tủ vật chứng B - Ngăn 05',
                'description' => 'Tem niêm phong thu tại khu vực kho.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case2)->id,
                'qr_code' => 'HS0002-VC007',
                'type' => Product::TYPE_OTHER,
                'name' => 'Mẫu bụi thu trên sàn',
                'sku' => 'VC-B-007',
                'location' => 'Tủ mẫu vi lượng - Ngăn 02',
                'description' => 'Mẫu bụi thu bằng túi chuyên dụng.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],

            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC001',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Ly thủy tinh',
                'sku' => 'VC-C-001',
                'location' => 'Tủ vật chứng C - Ngăn 01',
                'description' => 'Ly thủy tinh thu tại bàn phòng khách.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC002',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Điện thoại di động',
                'sku' => 'VC-C-002',
                'location' => 'Tủ điện tử E - Ngăn 03',
                'description' => 'Điện thoại di động màu xanh, đã niêm phong.',
                'storage_status' => Product::STORAGE_STATUS_ASSESSMENT,
                'stock' => 0,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC003',
                'type' => Product::TYPE_DOCUMENT,
                'name' => 'Sổ tay cá nhân',
                'sku' => 'VC-C-003',
                'location' => 'Tủ hồ sơ C - Ngăn 01',
                'description' => 'Sổ tay cá nhân thu tại phòng ngủ.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC004',
                'type' => Product::TYPE_DIGITAL,
                'name' => 'Thẻ nhớ microSD',
                'sku' => 'VC-C-004',
                'location' => 'Tủ điện tử E - Ngăn 04',
                'description' => 'Thẻ nhớ microSD 64GB.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC005',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Áo khoác màu xám',
                'sku' => 'VC-C-005',
                'location' => 'Tủ vật chứng C - Ngăn 03',
                'description' => 'Áo khoác màu xám thu trong phòng.',
                'storage_status' => Product::STORAGE_STATUS_RETURNED,
                'stock' => 0,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC006',
                'type' => Product::TYPE_IMAGE,
                'name' => 'Ảnh chụp căn hộ',
                'sku' => 'VC-C-006',
                'location' => 'Ổ lưu trữ số 03',
                'description' => 'Bộ ảnh chụp tổng quan căn hộ.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC007',
                'type' => Product::TYPE_OTHER,
                'name' => 'Mẫu tóc thu tại hiện trường',
                'sku' => 'VC-C-007',
                'location' => 'Tủ mẫu sinh học - Ngăn 01',
                'description' => 'Mẫu tóc thu bằng túi chuyên dụng.',
                'storage_status' => Product::STORAGE_STATUS_DESTROYED,
                'stock' => 0,
            ],
            [
                'case_file_id' => optional($case3)->id,
                'qr_code' => 'HS0003-VC008',
                'type' => Product::TYPE_OBJECT,
                'name' => 'Chìa khóa kim loại',
                'sku' => 'VC-C-008',
                'location' => 'Tủ vật chứng C - Ngăn 04',
                'description' => 'Chùm chìa khóa kim loại gồm 3 chìa.',
                'storage_status' => Product::STORAGE_STATUS_IN_STORAGE,
                'stock' => 1,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['qr_code' => $product['qr_code']],
                array_merge($product, [
                    'price' => 0,
                ])
            );
        }
    }
}
